### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by PizzaLovingNerd** [getsolus/solus-sc#21]
Whenever I launch new.py, I get an error about the queue module.

pizzalovingnerd@crisppc ~/Desktop/solus-sc $ python3 ./new.py
Traceback (most recent call last):
  File "./new.py", line 14, in <module>
    from xng.application import ScApplication
  File "/home/pizzalovingnerd/Desktop/solus-sc/xng/application.py", line 14, in <module>
    from .window import ScMainWindow
  File "/home/pizzalovingnerd/Desktop/solus-sc/xng/window.py", line 15, in <module>
    from .context import ScContext
  File "/home/pizzalovingnerd/Desktop/solus-sc/xng/context.py", line 15, in <module>
    from .executor import Executor
  File "/home/pizzalovingnerd/Desktop/solus-sc/xng/executor.py", line 15, in <module>
    from .op_queue import OperationQueue, Operation, OperationType
  File "/home/pizzalovingnerd/Desktop/solus-sc/xng/op_queue.py", line 14, in <module>
    import Queue
ModuleNotFoundError: No module named 'Queue'

**Comment by JoshStrobl** [comment]
The XNG version isn't going to be developed in python3, it'll be written in C. So while I'm not dismissing this report and saying it "isn't an issue", I'm going to close this as at no point in the future will this be addressed.
