### ISSUE TITLE
Crashes on launch

### ISSUE THREAD

**Issue by jwinnie** [getsolus/solus-sc#43]
**Reproduce**

* Download master from github
* `sudo eopkg it python-distutils-extra appstream-glib appstream-data && python3 setup.py build && sudo python3 setup.py install`
* `solus-sc`

**Traceback**

```
Traceback (most recent call last):
  File "/usr/bin/solus-sc", line 4, in <module>
    __import__('pkg_resources').run_script('solus-sc==22.0', 'solus-sc')
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib64/python3.7/site-packages/solus_sc-22.0-py3.7.egg/EGG-INFO/scripts/solus-sc", line 15, in <module>
    from solus_sc.application import ScApplication
  File "/usr/lib/python3.7/site-packages/solus_sc-22.0-py3.7.egg/solus_sc/application.py", line 14, in <module>
    from .main_window import ScMainWindow
  File "/usr/lib/python3.7/site-packages/solus_sc-22.0-py3.7.egg/solus_sc/main_window.py", line 14, in <module>
    from .appsystem import AppSystem
  File "/usr/lib/python3.7/site-packages/solus_sc-22.0-py3.7.egg/solus_sc/appsystem.py", line 16, in <module>
    from .media_fetcher import ScMediaFetcher
  File "/usr/lib/python3.7/site-packages/solus_sc-22.0-py3.7.egg/solus_sc/media_fetcher.py", line 83
    os.makedirs(cacheDir, 00755)
                              ^
SyntaxError: invalid token
```

**Comment by JoshStrobl** [comment]
It's not a python3 application...

Use the Software Center from the repo.

**Comment by jwinnie** [comment]
How am I supposed to build master then?
